### ISSUE TITLE
Cannot run the unity environment

### ISSUE THREAD

**Issue by AnyiRao** [xavierpuigf/virtualhome_unity#1]
Hello Dear Xavier,

Thanks for your great work! When I used Unity 2018.4.4.f1 (as the project suggested, installed from Unity Hub) to open the project (without any modification, tested both on ubuntu16 and mac os big sur), I encountered the following errors. 

Are these due to the reason that I miss installing some supporting packages?
![issues](https://user-images.githubusercontent.com/31238196/125898189-b9481bee-de12-4eb3-b3f6-3b4fb4446c40.png)

Thanks in advance.
Best,

**Comment by xavierpuigf** [comment]
Hi @AnyiRao, the latest version of the simulator is actually run with Unity 2019.X, but the reason you are getting this issue is because in order to make the simulator work you need to install external packages. In particular, you need to install FinalIK and Complete Home Interior Pack, listed here:
https://github.com/xavierpuigf/virtualhome_unity/blob/master/doc/third_party.md

You don't really need the modern house pack, it just includes extra assets
