### ISSUE TITLE
It seems the Unity version document should be updated

### ISSUE THREAD

**Issue by Xander23333** [xavierpuigf/virtualhome_unity#11]
@kswain98 Hi, I met the same question about Navmesh, and I find a closed issue has solved it. It seems you'd better update the document soon about the Unity version to avoid others meeting this problem. 

What else, I want to ask that has this project using NSM. I found a branch named `NSM_incoporation` and there is some code of NSM in it.

**Comment by kswain98** [comment]
Hi @Xander23333! Thanks for letting me know! All the documentation will be updated this weekend. We are constantly pushing updates to the procedural_generation branch which will be merged as the master branch by Monday.

Regarding the NSM question, @xavierpuigf might have the answer for this.

If you are interested you can join the Discord channel, since you might get a faster response: https://discord.gg/f3U92kUu4b
