### ISSUE TITLE
How can I add new scenes to the simulator?

### ISSUE THREAD

**Issue by QHFang** [xavierpuigf/virtualhome_unity#12]
If I have the mesh of another scene and the objects in it, what do I need to do to make the simulator work well with the new scene.

I found the documentation about adding new objects, but add scenes is more difficult.

**Comment by kswain98** [comment]
Hi @QHFang! Sorry for the delayed response! I suggest that you use the procedural_generation branch to start developing your new environments.

With the new version (procedural_generation branch) you can convert your environments into prefabs and instantiate them during runtime. All you have to do is create a prefab and drag-and-drop the chosen prefab into the "Gameobject" inspector window. 

If you just want to add new objects to current environments, you can open a prefab of Home_x (located in the Assets > Resources > Floorplan > Release > Home and then double click on a home and add your objects in that environment. Remember to add new objects prefab name into the Json files.

Let me know if you need any help or want me to clarify things for you further. Please join the Discord channel if you want, since it's easier for me and other to help you out faster. Discord link: https://discord.gg/f3U92kUu4b
